openapi: 3.0.0
info:
    title: TasteHolic API
    description: TasteHolic API 서버 문서
    version: 1.0.0
servers:
    - url: http://localhost:3000 # 추후 수정 필요
      description: Local server
paths:
    /home/recommend:
        get:
            summary: 추천 칵테일 가져오기
            description: 매일 랜덤으로 칵테일을 추천.
            responses:
                200:
                    description: 추천된 칵테일 정보
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    id:
                                        type: integer
                                        format: int64  # bigint를 표현
                                        example: 12345
                                    name:
                                        type: string
                                        example: "GOD FATHER"
                                    image:
                                        type: string
                                        example: "https://example.com/images/godfather.png"
                                    scent:
                                        type: string
                                        example: "아몬드, 바닐라, 견과류"
                                    taste:
                                        type: string
                                        example: "부드러움, 달콤한 아몬드, 쌉싸름"
                                    aftertaste:
                                        type: string
                                        example: "긴 여운, 고소함, 아몬드의 잔향"
                                    timing:
                                        type: string
                                        example: "디저트와 함께, 가벼운 술자리에서"
                                    ingredient:
                                        type: string
                                        example: "스카치 위스키, 아마레토"
                                    alcohol_level:
                                        type: string
                                        example: "25%~30%"
                                    description:
                                        type: string
                                        example: "달콤한 아마레토와 강렬한 스카치 위스키, 묵직한 달콤함"
    /home/best-taste:
        get:
            summary: 인기 있는 칵테일 가져오기
            description: 최근에 열람이 많이 된 칵테일 리스트를 반환.
            responses:
                200:
                    description: 인기 있는 칵테일 리스트
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: object
                                    properties:
                                        id:
                                            type: integer
                                            format: int64  # bigint를 표현
                                            example: 12345
                                        name:
                                            type: string
                                            example: "트로피컬 마티니"
                                        image:
                                            type: string
                                            example: "https://example.com/images/tropicalmartini.png"
                                        description:
                                            type: string
                                            example: "아름답고 향긋한 트로피컬 마티니는 로맨틱한 대화의 훌륭한 촉매제가 될 거예요."
                                        views:
                                            type: number
                                            example: 1200
    /home/taste-mood:
        get:
          summary: 분위기별 칵테일 추천
          description: 특정 분위기에 어울리는 칵테일 리스트를 반환.
          parameters:
            - in: query
              name: mood
              schema:
                  type: string
          responses:
              200:
                description: 분위기별 추천 칵테일 리스트
                content:
                  application/json:
                    schema:
                      type: array
                      items:
                        type: object
                        properties:
                            id:
                                type: integer
                                format: int64  # bigint를 표현
                                example: 12345
                            name:
                                type: string
                                example: "트로피컬 마티니"
                            image:
                                type: string
                                example: "https://example.com/images/tropicalmartini.png"
                            mood:
                                type: string
                                example: "사랑하는 사람과 로맨틱한 TASTE MOOD"
    /holic-now:
      get:
        summary: 최신 유튜브 영상 가져오기
        description: 칵테일 관련 최신 유튜브 영상 URL 제공.
        responses:
          200:
            description: 유튜브 영상 정보
            content:
              application/json:
                schema:
                  type: object
                  properties:
                      video_url:
                        type: string
                        example: "https://www.youtube.com/watch?v=abcd1234"
