openapi: 3.0.0
info:
    title: TasteHolic API
    description: TasteHolic API 서버 문서
    version: 1.0.0
servers:
    - url: http://localhost:3000 # 추후 수정 필요
      description: Local server
# 예시
paths:
    /home/recommend:
        get:
            summary: 추천 칵테일 가져오기
            description: 매일 랜덤으로 칵테일을 추천.
            responses:
                200:
                    description: 추천된 칵테일 정보
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    id:
                                        type: string
                                        example: "cocktail_123"
                                    name:
                                        type: string
                                        example: "Margarita"
                                    image:
                                        type: string
                                        example: "https://example.com/images/margarita.png"
                                    taste:
                                        type: string
                                        example: "Sweet & Sour"
                                    alcohol_level:
                                        type: number
                                        example: 15
                                    description:
                                        type: string
                                        example: "A refreshing cocktail with lime and tequila."
    /home/best-taste:
        get:
            summary: 인기 있는 칵테일 가져오기
            description: 최근에 열람이 많이 된 칵테일 리스트를 반환.
            responses:
                200:
                    description: 인기 있는 칵테일 리스트
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: object
                                    properties:
                                        id:
                                            type: string
                                            example: "cocktail_456"
                                        name:
                                            type: string
                                            example: "Old Fashioned"
                                        image:
                                            type: string
                                            example: "https://example.com/images/old_fashioned.png"
                                        views:
                                            type: number
                                            example: 1200
    /home/taste-mood:
        get:
          summary: 분위기별 칵테일 추천
          description: 특정 분위기에 어울리는 칵테일 리스트를 반환.
          parameters:
            - in: query
              name: mood
              schema:
                  type: string
              
          responses:
              200:
                description: 분위기별 추천 칵테일 리스트
                content:
                  application/json:
                    schema:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: string
                            example: "cocktail_789"
                          name:
                            type: string
                            example: "Cosmopolitan"
                          image:
                            type: string
                            example: "https://example.com/images/cosmopolitan.png"
                          mood:
                            type: string
                            example: "romantic"
    /holic-now:
      get:
        summary: 최신 유튜브 영상 가져오기
        description: 칵테일 관련 최신 유튜브 영상 URL 제공.
        responses:
          200:
            description: 유튜브 영상 정보
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    video_title:
                      type: string
                      example: "Top 5 Cocktails You Must Try!"
                    video_url:
                      type: string
                      example: "https://www.youtube.com/watch?v=abcd1234"
